version: 2.0

defaults: &defaults
  working_directory: /tmp/project
  docker:
    - image: circleci/ruby:2.4.3

save_cache: &save_cache
  save_cache:
    key: v1-bundle-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-bundle-{{ checksum "Gemfile.lock" }}

bundle: &bundle
  run: 
    name: Install Gems
    command: bundle install --path vendor/bundle

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *bundle
      - *save_cache
      - run:
          name: Build Site
          # jekyll returns an incorrect error code so we need to test for failure manually
          command: bundle exec rake build:prod && test -f _site/sitemap.xml
      - persist_to_workspace:
          root: .
          paths: ./*
      - store_artifacts:
          path: _site
          destination: /

  check_html:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *bundle
      - run:
          name: Check HTML
          command: bundle exec rake check:html

  check_spelling:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *bundle
      - run:
          name: Install Prerequisites
          command: "sudo apt-get update && sudo apt-get install aspell"
      - run: 
          name: Check Spelling
          command: bundle exec rake check:spelling

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *bundle
      - run:
          name: Deploy
          command: bundle exec rake deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - check_spelling:
          requires:
            - build
      - check_html:
          requires:
            - build
      - deploy:
          requires:
            - check_html
            - check_spelling
          filters:
            branches:
              only: develop
